### ISSUE TITLE
maxNativeZoom in functional tile layer

### ISSUE THREAD

**Issue by gwacker** [ismyrnow/Leaflet.functionaltilelayer#7] opened 2014-04-14 21:51 UTC
It seems I can pass minZoom and maxZoom as options into the functional tile layer, but passing in maxNativeZoom doesn't behave like it does in TileLayer

**Comment by ismyrnow** [comment] 2014-08-04 01:54
I'm not seeing this behavior. I tried it out by extending the basic example with the following code:

``` javascript
funcLayer2 = new L.TileLayer.Functional(function (view) {
  return 'http://otile1.mqcdn.com/tiles/1.0.0/sat/{z}/{y}/{x}.jpg'
    .replace('{z}', view.zoom)
    .replace('{x}', view.tile.row)
    .replace('{y}', view.tile.column);
  }, { maxNativeZoom: 10 });
map.addLayer(funcLayer2);
```

The result is as expected; the satellite tiles are only fetched up to layer 10, and beyond that, they are scaled client-side.

I'm going to close this for now, but feel free to provide an example (jsbin/jsfiddle) if you feel the issue is still there.

**Closed as completed by ismyrnow** 2014-08-04 01:54 UTC
Labels: invalid
